---
# Override file using a container for DB

services:
  osticket:
    environment:
      MYSQL_HOST: db.xander.local
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
    depends_on:
      - db
  db:
    container_name: osticket-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306/tcp

    x-network:
      Ingress:
        Services:
          - Name: osticket
      x-cloudmap: PrivateNamespace

x-cloudmap:
  PrivateNamespace:
    Name: xander.local # Change to whatever you'd want it to be. Required to resolve `db.xander.local`
